-- Studio Baton — PostgreSQL / Supabase schema.
--
-- Matches the default names in src/baton/defaults.yaml. Run it in the Supabase
-- SQL editor, or with psql against a self-hosted PostgREST database.
--
-- Row Level Security is enabled with no policies, which denies everything by
-- default. Add policies for the role your key uses before Baton can read —
-- shipping a schema that is readable by anyone with the anon key would be a
-- worse default than one that visibly needs a decision.

CREATE TABLE IF NOT EXISTS pieces (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          text NOT NULL,
    source_link    text NOT NULL DEFAULT '',
    practice_track text NOT NULL DEFAULT '',
    sheet_link     text NOT NULL DEFAULT '',
    created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS learners (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             text NOT NULL UNIQUE,
    instrument       text NOT NULL DEFAULT '',
    tone             text NOT NULL DEFAULT 'standard',
    has_instrument   boolean NOT NULL DEFAULT false,
    current_piece_id bigint REFERENCES pieces (id) ON DELETE SET NULL,
    -- Whether they still study here. Deactivating removes a learner from
    -- matching and rosters; nothing is ever deleted, and `learner activate`
    -- brings them back.
    is_active        boolean NOT NULL DEFAULT true,
    -- Fully out of the way: hidden even from `learner list --all`, unlike
    -- is_active. NULL means not trashed. `learner trash`/`learner untrash`
    -- are the only things that ever touch this. Nothing is ever deleted.
    deleted_at       timestamptz DEFAULT NULL,
    created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sessions (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learner_id bigint NOT NULL REFERENCES learners (id) ON DELETE CASCADE,
    number     integer NOT NULL,
    doc_id     text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (learner_id, number)
);

CREATE TABLE IF NOT EXISTS works (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learner_id     bigint NOT NULL REFERENCES learners (id) ON DELETE CASCADE,
    title          text NOT NULL,
    type           text NOT NULL DEFAULT 'performance',
    video_link     text NOT NULL DEFAULT '',
    -- Optional second home of the recording; see sqlite.sql on why it exists.
    drive_link     text NOT NULL DEFAULT '',
    performed_date date,
    created_at     timestamptz NOT NULL DEFAULT now()
);

-- One row per recurring weekly hour: the day a learner comes and the time
-- their lesson starts. The words in `weekday` are the same seven English day
-- names the Notion dashboard tags use, so the two never need translating.
-- The calendar holds the booked lessons; this table holds the standing
-- weekly pattern behind them.
CREATE TABLE IF NOT EXISTS lesson_slots (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learner_id bigint NOT NULL REFERENCES learners (id) ON DELETE CASCADE,
    weekday    text NOT NULL,
    start_time text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (learner_id, weekday, start_time)
);

CREATE INDEX IF NOT EXISTS idx_sessions_learner ON sessions (learner_id, number);
CREATE INDEX IF NOT EXISTS idx_works_learner    ON works (learner_id, performed_date DESC);
CREATE INDEX IF NOT EXISTS idx_lesson_slots_learner ON lesson_slots (learner_id, weekday, start_time);

ALTER TABLE learners ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE pieces   ENABLE ROW LEVEL SECURITY;
ALTER TABLE works    ENABLE ROW LEVEL SECURITY;
ALTER TABLE lesson_slots ENABLE ROW LEVEL SECURITY;

-- Example policy for a service-role key. Adjust to your own auth model; do not
-- grant this to the anon role unless the data is genuinely public.
--
--   CREATE POLICY baton_service_all ON learners
--     FOR ALL TO service_role USING (true) WITH CHECK (true);
